version: '3.8'
services:
  web:
    build:
      context: ../
      dockerfile: dev_tools/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=anverali
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: anverali
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
